name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_BASE_URL: https://openrouter.ai/api/v1
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MODEL_NAME: openai/gpt-oss-120B
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1
      - run: uv sync
      - run: uv run pytest
